In [2]:
import numpy as np

In [2]:
np.array(5)

array(5)

In [3]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
#convert range(0,10) into a numpy array
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(2) #gives 2 random values between 0 and 1

array([0.06940557, 0.28923781])

In [17]:
np.random.randint(1,100)

66

In [18]:
np.random.randint(1,100,10)

array([66, 78, 98, 94,  2, 91, 91, 61, 86, 14])

In [19]:
arr = np.arange(25)

In [20]:
#Reshaping the array into 2D
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [22]:
arr.reshape(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
arr = arr.reshape(5,5)

In [24]:
arr.max() #or arr.min()

24

In [25]:
arr.shape

(5, 5)

In [26]:
arr.argmax(axis = 0) 

array([4, 4, 4, 4, 4], dtype=int64)

In [27]:
arr.argmax()

24

# Broadcasting

In [28]:
#Numpy arrays differ from normal python list because of their ability to broadcast

In [29]:
arr = np.arange(11)

In [30]:
arr[0:5] = 100
arr
#Normal python array will give type error

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [31]:
slice_of_arr = arr[0:6]
#If we change values in this slice, original array will also get updated
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [32]:
slice_of_arr[:] = 99

In [33]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [35]:
arr_copy = arr.copy()

In [36]:
#Indexing elements of more than 1D arrays

In [37]:
arr_2D = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [38]:
arr_2D[1] #Indexing row

array([20, 25, 30])

In [39]:
#Format is arr_2D[row][col] or arr_2D[row,col]

In [40]:
arr_2D[1,0]

20

In [41]:
arr_2D[1][0]

20

In [43]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [44]:
arr_2D[:,1:2]

array([[10],
       [25],
       [40]])

In [46]:
arr_2D[1:,:2]

array([[20, 25],
       [35, 40]])

In [48]:
arr = np.array([['a','b','c','d'],['e','f','g','h'],['i','j','k','l']])
arr

array([['a', 'b', 'c', 'd'],
       ['e', 'f', 'g', 'h'],
       ['i', 'j', 'k', 'l']], dtype='<U1')

In [49]:
arr[1:,1:]

array([['f', 'g', 'h'],
       ['j', 'k', 'l']], dtype='<U1')

In [50]:
arr[:,2]

array(['c', 'g', 'k'], dtype='<U1')

In [51]:
arr[2,:]

array(['i', 'j', 'k', 'l'], dtype='<U1')

In [9]:
arr2D = np.zeros((10,10))
arr2D

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
arr_length = arr2D.shape[1]

In [11]:
#Set up array

for i in range(arr_length):
    arr2D[i] = i

arr2D

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [12]:
#Fancy indexing
arr2D[[2,4,6,8]] #Prints specified rows

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [15]:
arr2D[[6,4,2,7]] #allows in any order

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [14]:
arr2D[:,[2,4,6]] #Prints specied columns

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.],
       [8., 8., 8.],
       [9., 9., 9.]])

In [17]:
#Selection
arr =np.arange(1,11)
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [18]:
bool_arr = arr>4

In [19]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [20]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Numpy operations

In [23]:
arr = np.arange(10)

In [24]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
arr/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [28]:
1/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [29]:
arr/arr

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [30]:
#Universal array functions
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [31]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [32]:
np.max(arr)

9

In [33]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [34]:
np.log(arr)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])